name: Android CI
on: workflow_dispatch
jobs:
 build:

    runs-on: ubuntu-latest

    steps:
    - name: Decode Keystore
      env:
        ENCODED_STRING: ${{ secrets.RELEASE_KEYSTORE }}
      run: echo -n $ENCODED_STRING | base64 -d > release_keystore.jks;ls;pwd
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew;echo -n $ENCODED_STRING | base64 -d > release_keystore.jks;ls;pwd
    - name: Build with Gradle
      run: ./gradlew signingReport;ls
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
