name: Build release app
on: workflow_dispatch
jobs:
 build:
    runs-on: ubuntu-latest
    environment: main-environment

    steps:
    - uses: actions/checkout@v4
    - name: Configure JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Execute permission to gradlew
      run: chmod +x gradlew

    - name: Create keystore file
      run: echo -n ${{ secrets.RELEASE_KEYSTORE }} | base64 -d > release_keystore.jks

    - name: Build release with Gradle
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      run: ./gradlew assembleRelease
      
    - name: Upload release app
      uses: actions/upload-artifact@v2
      with:
        name: Release app
        path: app/build/outputs/apk/release/app-release.apk
